[package]
name = "gb-emu"
version = "0.1.0"
authors = ["Takeshi Masumoto <take44444.general@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.70"
crc = "1.3"
env_logger = "0.10.0"
log = "0.4.17"
sdl2 = "0.35.2"
