/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function __wbg_gameboyhandle_free(a: number): void;
export function gameboyhandle_new(a: number, b: number, c: number, d: number): number;
export function gameboyhandle_set_apu_callback(a: number, b: number): void;
export function gameboyhandle_title(a: number, b: number): void;
export function gameboyhandle_save(a: number): number;
export function gameboyhandle_to_json(a: number, b: number): void;
export function gameboyhandle_to_json2(a: number, b: number): void;
export function gameboyhandle_connect(a: number, b: number, c: number): void;
export function gameboyhandle_sync(a: number, b: number, c: number, d: number, e: number): void;
export function gameboyhandle_disconnect(a: number): void;
export function gameboyhandle_emulate_cycle(a: number): number;
export function gameboyhandle_frame_buffer(a: number): number;
export function gameboyhandle_key_down(a: number, b: number, c: number): void;
export function gameboyhandle_key_up(a: number, b: number, c: number): void;
export function gameboyhandle_key_down2(a: number, b: number, c: number): void;
export function gameboyhandle_key_up2(a: number, b: number, c: number): void;
export function __wbg_audiohandle_free(a: number): void;
export function audiohandle_new(): number;
export function audiohandle_append(a: number, b: number, c: number): void;
export function audiohandle_length(a: number): number;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export const __wbindgen_export_2: WebAssembly.Table;
export function _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h4adb2439f653c6ac(a: number, b: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
